import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "min-h-[100svh]"}>
        <ClerkProvider>
          <TooltipProvider delayDuration={100}>
            <div className="absolute inset-0 flex">
              <div className="h-full flex-grow">{children}</div>
            </div>
          </TooltipProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
